# Generated by Django 4.2.13 on 2024-12-12 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workexperience', '0003_workexperience_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='description',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='endDate',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='startDate',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
        ),
    ]
